### ISSUE TITLE
Improve Detail Views

### ISSUE THREAD

**Issue by ctot-nondef** [acdh-oeaw/thomas-bernhard-global#1]
- [x] some available data is not yet visible in the detail views:
  - [x] year
  - [x] publishing house
  - [x] series

- [x] display needs to be adjusted
  - [x] consistently display labels/keys along with values
  - [x] visually distinguish between keys and values
  - [x] separate multiple categories with something other than commas

**Comment by ctot-nondef** [comment]
- [ ] make details more table like

**Comment by kevinstadler** [comment]
Final tweaks added with f8c7d9d
