### ISSUE TITLE
flatten (sub)categories into single facett

### ISSUE THREAD

**Issue by ctot-nondef** [acdh-oeaw/thomas-bernhard-global#6]
the category filter in the [works](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/works/novels) section should be flattened into a single facett list (as of now, only prose has subcategories anyway)

**Comment by kevinstadler** [comment]
Flat work category facetting was implemented in d7332cbd9cfa91a302466c22dc7fc787308dffaf
