### ISSUE TITLE
only display works of selected category

### ISSUE THREAD

**Issue by ctot-nondef** [acdh-oeaw/thomas-bernhard-global#7]
in the  works section, when a category is selected, the works filter should only provide works of that category

right now, it also displays works of different categories, when they were published in a common collective volume, ie [here](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/works/letterspeechinterview)

**Comment by kevinstadler** [comment]
Wie erwartet hat sich die Kategorie von einem Grossteil der (214) zugrundeliegenden Bernhard-Werke aus den explizit vermerkten Kategorien der Publikationen herleiten lassen -- nur bei den folgenden 38 Werken ist die Kategorie nicht eindeutig, bitte um Input welche Kategorie zugewiesen werden soll.

Bei 9 weiteren Werken (siehe weiter unten) würden sich durch verschiedene Publikationen eindeutige, jedoch widersprüchliche Kategorien herleiten lassen, was darauf hindeutet dass eine der Publikationen womöglich selber falsch kategorisiert ist -- minimale Abänderungs-Vorschläge um den Datensatz konsistent zu machen sind auch dort angeführt, bitte um Feedback!

(Bitte zu beachten dass die auf den zur Zeit online verlinkten Detail-Seiten aufscheinenden Kategorien womöglich nicht denen entsprechen die in dieser Liste angeführt sind, die Aussagen über Kategorisierungen in der Liste beziehen sich auf den Rohdatensatz im OpenRefine, die Kategorien auf der Webseite sind bereits automatisch (womöglich inkorrekt!) bereinigte!)

## Werke mit unbekannten/uneindeutigen Kategorien

1. *Wittgensteins Neffe* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [fra_051](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_051)): Werk-Kategorie nicht eindeutig:
    - [ ] bei diesem Eintrag ist für das Werk keine GND vermerkt -- wenn man die GND ` 4509408-1 ` ergänzt wäre die Kategorie eindeutig `novellas & short prose`
1. *Mein Glückliches Österreich* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [fra_059](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_059)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `drama & libretti`, `letters, speeches, interviews`, `novellas & short prose`
1. *Junge Köpfe* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [fra_083](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_083)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `poetry`, `letters, speeches, interviews`, `novellas & short prose`
1. *Meine eigene Einsamkeit* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [fra_083](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_083)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `poetry`, `letters, speeches, interviews`, `novellas & short prose`
1. *Gerichtschroniken (Ein paar saure Zuckerl* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [fra_083](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_083)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `poetry`, `letters, speeches, interviews`, `novellas & short prose`
1. *Selbstmord in der Landesheilanstalt* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [fra_083](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_083)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `poetry`, `letters, speeches, interviews`, `novellas & short prose`
1. *Vielgeliebt und nie bezahlt* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [fra_083](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_083)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `poetry`, `letters, speeches, interviews`, `novellas & short prose`
1. *Gastspiel am Landesgericht* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [fra_083](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_083)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `poetry`, `letters, speeches, interviews`, `novellas & short prose`
1. *Ernestine kontra Lucie* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [fra_083](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_083)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `poetry`, `letters, speeches, interviews`, `novellas & short prose`
1. *Paris* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [fra_083](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_083)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `poetry`, `letters, speeches, interviews`, `novellas & short prose`
1. *Die Frau aus Gußwerk* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [fra_083](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_083)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `poetry`, `letters, speeches, interviews`, `novellas & short prose`
1. *In Rom* (GND None, 2 Veröffentlichung(en), erstmals gesehen in [fra_083](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_083)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `poetry`, `letters, speeches, interviews`, `novellas & short prose`
1. *Erklärung* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [fra_083](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_083)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `poetry`, `letters, speeches, interviews`, `novellas & short prose`
1. *Thomas Bernhard und Siegfried Unseld (Auszüge)* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [fra_083](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_083)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `poetry`, `letters, speeches, interviews`, `novellas & short prose`
1. *Unseld* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [fra_083](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_083)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `poetry`, `letters, speeches, interviews`, `novellas & short prose`
1. *Politische Morgenandacht* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [fra_084](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_084)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `letters, speeches, interviews`, `drama & libretti`, `novellas & short prose`
1. *Schriftstellerberuf heute. Die Komödie der Eitelkeit* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [fra_084](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_084)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `letters, speeches, interviews`, `drama & libretti`, `novellas & short prose`
1. *Bernhards Plädoyer. Zur Wiener Gerichtsverhandlung „Holzfällen“ betreffend* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [fra_084](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_084)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `letters, speeches, interviews`, `drama & libretti`, `novellas & short prose`
1. *Vranitzky. Eine Erwiderung* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [fra_084](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_084)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `letters, speeches, interviews`, `drama & libretti`, `novellas & short prose`
1. *Bernhard gegen Europalia. Kein Gastspiel des „Theatermachers“ in Brüssel?)* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [fra_084](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_084)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `letters, speeches, interviews`, `drama & libretti`, `novellas & short prose`
1. *Die Billigesser (Auszug)* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [fra_084](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_084)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `letters, speeches, interviews`, `drama & libretti`, `novellas & short prose`
1. *Thomas Bernhard an die Redaktion des Watzmann, 1.4.198* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [fra_084](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_084)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `letters, speeches, interviews`, `drama & libretti`, `novellas & short prose`
1. *die rosen der einöde* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [fra_084](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_084)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `letters, speeches, interviews`, `drama & libretti`, `novellas & short prose`
1. *Warum fürchte ich mein Altern* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [fra_088](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_088)): Werk-Kategorie nicht eindeutig:
    - [ ] Publikation hat keine Kategorien vermerkt!
1. *???* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [fra_088](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_088)): Werk-Kategorie nicht eindeutig:
    - [ ] Publikation hat keine Kategorien vermerkt!
1. *Im Garten der Mutter* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [fra_088](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_088)): Werk-Kategorie nicht eindeutig:
    - [ ] Publikation hat keine Kategorien vermerkt!
1. *Im Tal* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [pol_047](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/pol_047)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `poetry`, `letters, speeches, interviews`, `novels`, `novellas & short prose`
1. *Krieger* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [pol_047](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/pol_047)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `poetry`, `letters, speeches, interviews`, `novels`, `novellas & short prose`
1. *Eine Strophe für Padraic Colum* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [pol_047](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/pol_047)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `poetry`, `letters, speeches, interviews`, `novels`, `novellas & short prose`
1. *Geburtstagsode* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [pol_047](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/pol_047)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `poetry`, `letters, speeches, interviews`, `novels`, `novellas & short prose`
1. *Morgen* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [pol_047](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/pol_047)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `poetry`, `letters, speeches, interviews`, `novels`, `novellas & short prose`
1. *Beschreibung einer Familie* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [pol_047](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/pol_047)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `poetry`, `letters, speeches, interviews`, `novels`, `novellas & short prose`
1. *Jetzt im Frühling* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [pol_047](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/pol_047)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `poetry`, `letters, speeches, interviews`, `novels`, `novellas & short prose`
1. *An H. W.* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [pol_047](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/pol_047)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `poetry`, `letters, speeches, interviews`, `novels`, `novellas & short prose`
1. *Holzfällen (Auszug)* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [pol_047](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/pol_047)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `poetry`, `letters, speeches, interviews`, `novels`, `novellas & short prose`
1. *Der Literaturpreis der Freien und Hansestadt Bremen* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [pol_047](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/pol_047)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `poetry`, `letters, speeches, interviews`, `novels`, `novellas & short prose`
1. *Ereignisse (Auswahl)* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [pol_047](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/pol_047)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `poetry`, `letters, speeches, interviews`, `novels`, `novellas & short prose`
1. *Drei Tage (Auszug)* (GND None, 1 Veröffentlichung(en), erstmals gesehen in [slw_022](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/slw_022)): Werk-Kategorie nicht eindeutig:
    - [ ] eine von: `letters, speeches, interviews`, `drama & libretti`

## Werke mit widersprüchlichen Kategorien

39. *Wittgensteins Neffe*: ist in [aze_001](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/aze_001) das als `novels` kategorisiert ist, in anderen Publikationen (z.B. [alb_002](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/alb_002)) dagegen als `novellas & short prose`
    - [ ] wahrscheinlicher Fix: `aze_001`'s Kategorie von `novels` auf `novellas & short prose` ändern
1. *Frühling*: ist in [cze_035](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/cze_035) das als `novellas & short prose` kategorisiert ist, in anderen Publikationen (z.B. [bul_006](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/bul_006)) dagegen als `drama & libretti`
    - [ ] wahrscheinlicher Fix: `cze_035`'s Kategorien zusätzlich zu `novellas & short prose` um `drama & libretti` ergänzen
1. *Ritter, Dene, Voss*: ist in [cze_046](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/cze_046) das als `autobiography` kategorisiert ist, in anderen Publikationen (z.B. [bul_005](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/bul_005)) dagegen als `drama & libretti`
    - [ ] wahrscheinlicher Fix: `cze_046`'s Kategorie von `autobiography` auf `drama & libretti` ändern
1. *Meine Preise. Eine Bilanz*: ist in [eng_007](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/eng_007) das als `autobiography` kategorisiert ist, in anderen Publikationen (z.B. [bra_007](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/bra_007)) dagegen als `letters, speeches, interviews`
    - [ ] wahrscheinlicher Fix: `eng_007`'s Kategorie von `autobiography` auf `letters, speeches, interviews` ändern
1. *Drei Tage*: ist in [fra_075](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/fra_075) das als `novellas & short prose` kategorisiert ist, in anderen Publikationen (z.B. [eng_079](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/eng_079)) dagegen als `letters, speeches, interviews`
    - [ ] wahrscheinlicher Fix: `fra_075`'s Kategorie von `novellas & short prose` auf `letters, speeches, interviews` ändern
1. *André Müller im Gespräch mit Thomas Bernhard*: ist in [ita_019](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/ita_019) das als `drama & libretti` kategorisiert ist, in anderen Publikationen (z.B. [eng_096](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/eng_096)) dagegen als `letters, speeches, interviews`
    - [ ] wahrscheinlicher Fix: `ita_019`'s Kategorie von `drama & libretti` auf `letters, speeches, interviews` ändern oder zusätzlich zu `drama & libretti` um `letters, speeches, interviews` ergänzen
1. *André Müller im Gespräch mit Thomas Bernhard*: ist in [ita_020](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/ita_020) das als `drama & libretti` kategorisiert ist, in anderen Publikationen (z.B. [eng_096](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/eng_096)) dagegen als `letters, speeches, interviews`
    - [ ] wahrscheinlicher Fix: `ita_020`'s Kategorien zusätzlich zu `drama & libretti` um `letters, speeches, interviews` ergänzen
1. *Der Wetterfleck*: ist in [jpn_022](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/jpn_022) das als `drama & libretti` kategorisiert ist, in anderen Publikationen (z.B. [eng_091](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/eng_091)) dagegen als `novellas & short prose`
    - [ ] wahrscheinlicher Fix: `jpn_022`'s Kategorie von `drama & libretti` auf `novellas & short prose` ändern
1. *Der Stimmenimitator*: ist in [slw_011](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/slw_011) das als `drama & libretti` kategorisiert ist, in anderen Publikationen (z.B. [bra_008](https://thomas-bernhard-global.acdh-ch-dev.oeaw.ac.at/publication/bra_008)) dagegen als `novellas & short prose`
    - [ ] wahrscheinlicher Fix: `slw_011`'s Kategorie von `drama & libretti` auf `novellas & short prose` ändern
